#!/usr/bin/env Rscript
## Purpose: Script makes boxplot of hypoxia scores of TCGA, TCGA normal and GTEX with all the cancer types (with the cancer type of interes at the far left) and marks the hypoxia score of sample of interest with  a red line:
##
## Author: Ximena/Tinu Thomas
##
## Manual
## ------
##
## In command line type:
## Rscript --vanilla Rplot.R <sample> <cancerType> <tcga_and_gtex_hypoxiaScore File> <sample_hypoxia_scores.tsv> <output_dir> <out_allcancerplot> <out_skinplot>
##  <sample>                            - sampleName
##  <cancerType>                        - Tumor type
##  <tcga_and_gtex_hypoxiaScore File>   - resource file which has hypoxia scores of TCGA, matched normal and GTEX samples>
##  <tumor hypoxiaScore File>           - the file which has hypoxia score of the tumor, generated by the hypoxia score pipeline
##  <out_allcancerplot>                 - output all cancer plot name
##  <out_cancerTypeplot>                      - output CancerType plot name
###############################################################################

library(ggplot2)
args <- commandArgs(trailingOnly = TRUE)
sample_name <- args[1]
sample_CancerType <- args[2]
tcga_gtexFile <- args[3]
hypoxia_scoreFile <- args[4]
outdir <- args[5]
out_allcancer_boxplot <- args[6]
out_skin_boxplot <- args[7]

sampleList_hypoxiaFiles <- list.files(path=outdir, pattern=".hypoxia_score.tsv$") 

all_tumors=read.table(tcga_gtexFile, header=TRUE)


#Reorder the factors of the columns cancer_type_match so the cancer type of interest (in this case skin melanoma) appears first:
all_tumors$cancer_type_match=factor(all_tumors$cancer_type_match, levels = c("SKCM", "OV", "BLCA", "BRCA", "CHOL", "COAD", "ESCA", "GBM", "HNSC", "KICH", "KIRC", "KIRP", "LIHC", "LUAD", "LUSC", "PAAD", "PRAD", "READ", "STAD", "THCA", "UCEC"))

cancer_type=c("SKCM", "OV", "BLCA", "BRCA", "CHOL", "COAD", "ESCA", "GBM", "HNSC", "KICH", "KIRC", "KIRP", "LIHC", "LUAD", "LUSC", "PAAD", "PRAD", "READ", "STAD", "THCA", "UCEC")

#Create a new column of the intersection of "study" and whether a sample is tumor or not "is_normal":
all_tumors$joint=interaction(all_tumors$is_normal, all_tumors$study)

##################################################
## Plot 1 - All cancer plot
##################################################

sample_tumor=read.table(hypoxia_scoreFile, header=TRUE)

tumor_hypoScore=sample_tumor$pathway_score

pdf(out_allcancer_boxplot, width=20)

plot_allcancers=ggplot(data=all_tumors, aes(x=cancer_type_match, y=hypoxia_score, fill=joint)) + geom_boxplot(outlier.shape=NA,  width=0.45,position = position_dodge(0.45, preserve="single") ) 

plot_allcancers + geom_hline(aes(yintercept=tumor_hypoScore), colour="#DF1E1E", size=1) + geom_text(aes(0,tumor_hypoScore, label = tumor_hypoScore, hjust=1) ) + xlab("Cancer type")+ ylab("Hypoxia score") + theme_bw(base_size = 12) + theme(axis.text.x = element_text(angle = 90)) +  theme(legend.position="bottom") + scale_fill_manual(values = c("#ACBDDA", "#F5AB18", "#D4D2CD"), name= "Sample type", breaks=c("FALSE.tcga", "TRUE.tcga", "TRUE.gtex"), labels=c("Tumor (TCGA)", "Matched normal (TCGA)","Normal (GTEx)")) 

dev.off()


##################################################
## Plot 2 - Cancer type specific plot
##################################################

## Summary front page

#This is to make the summary page plot showing the distribution of all hypoxia scores for the tissue/cancer type of interest and where do TuPro and a specific sample (the one of the report) fall within the TCGA distribution.

#Select only SKCM (or the cancer type of interest)
skcm=subset(all_tumors, cancer_type_match == "SKCM", select= c(sample_id, hypoxia_score, is_normal))
#Select only OV (or the cancer type of interest)
ov=subset(all_tumors, cancer_type_match == "OV", select= c(sample_id, hypoxia_score, is_normal))
#fileList=unlist(strsplit(sampleList_hypoxiaFiles, ","))
counter=0
datalist = list()
#Loping through each hypoxia score file in the outdir
for(hypoFile in sampleList_hypoxiaFiles){
    print(hypoFile)
    print('****')
    counter = counter+1
    baseFile=(basename(hypoFile))
    #sample_id=tools::file_path_sans_ext(baseFile)
    hypoFile=paste(outdir, '/', hypoFile, sep='')
    tumorData=read.table(hypoFile, header=TRUE)
    sample_id=tumorData$sample_id
    hypoxia_score=tumorData$pathway_score
    is_normal=tumorData$is_normal
    df=data.frame(sample_id, hypoxia_score, is_normal) #getting sampleID, hypoxia_score and normal status for all samples
    datalist[[counter]] <-df
    }
big_data = do.call(rbind, datalist)
if ( sample_CancerType == 'MELANOMA' ) {
    print("melanoma")
    all_samples=rbind(skcm, big_data)
    print('___________________')
} else if (sample_CancerType == 'OVARIAN') {
    print("ovarian")
    all_samples=rbind(ov, big_data)
}

sample_name_plot=paste(sample_name, '.all.expression.tsv', sep='')

# Plotting the Skin boxplot
pdf(out_skin_boxplot)
#print(sample_id)
#print((all_samples))
#sample_IDs = all_samples[which(all_samples$sample_id %in% (big_data$sample_id)),]
tumor_ID = all_samples[which(all_samples$sample_id == sample_name_plot),]

#Data points for all samples
#plotSUMMARY= ggplot(data = all_samples, aes(x=is_normal, y=hypoxia_score, group=is_normal))+ geom_boxplot(fill=c("khaki1","#D4D2CD"),lwd=1 ) + geom_point(data= sample_IDs, aes(x=is_normal, y=hypoxia_score, colour='Other Tumors'), size=8) + geom_point(data=tumor_ID, aes(x=is_normal, y=hypoxia_score, colour=sample_name), size=12) 

# Data point for only tumor of interest
plotSUMMARY= ggplot(data = all_samples, aes(x=is_normal, y=hypoxia_score, group=is_normal))+ geom_boxplot(fill=c("khaki1","#D4D2CD"),lwd=1 ) +  geom_point(data=tumor_ID, aes(x=is_normal, y=hypoxia_score, colour=sample_name), size=12) 

if ( sample_CancerType == 'MELANOMA' ) {
    plotSUMMARY + scale_x_discrete(name="Sample Type",labels=c("Melanoma(TCGA)","Skin(GTEx)")) +  theme(legend.title = element_blank()) 
} else if (sample_CancerType == 'OVARIAN') {
    plotSUMMARY + scale_x_discrete(name="Sample Type",labels=c("Ovarian(TCGA)","Ovarian(GTEx)")) +  theme(legend.title = element_blank()) 
}
dev.off()
